name:                thump
version:             0.1.0.0
github:              "jameshales/thump"
license:             BSD3
author:              "James Hales"
maintainer:          "james@jameshales.org"
copyright:           "James Hales 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jameshales/thump#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.0.0

library:
  source-dirs: src

executables:
  thump-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thump

tests:
  thump-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck == 2.*
    - hspec == 2.*
    - thump
